apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: cafe
spec:
  http-snippets: |
    limit_req_zone $remote_addr zone=perip:1m rate=3r/m;
    map $http_apikey $api_client_name {
    default "";

    "7B5zIqmRGXmrJTFmKa99vcit" "client_one";
    "QzVV6y1EmQFbbxOfRCwyJs35" "client_two";
    "mGcjH8Fv6U9y3BVF9H3Ypb9T" "client_six";
    }
  host: cafe.example.com
  policies:
  - name: rate-limit-policy
  - name: webapp-policy
  tls:
    secret: cafe-secret
  server-snippets: |
   location = /_validate_apikey {
        internal;

        if ($http_apikey = "") {
            return 401; # Unauthorized
        }
        if ($api_client_name = "client_one") {
            return 403; # Forbidden
        }

        return 204; # OK (no content)
    }
  upstreams:
  - name: tea
    service: tea-svc
    port: 80
  - name: coffee
    service: coffee-svc
    port: 80
  routes:
  - path: /tea
    action:
      pass: tea
  - path: /coffee
    location-snippets: |
      auth_request /_validate_apikey;
    action:
      pass: coffee